# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adddata.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_adddata(object):
    def setupUi(self, adddata):
        adddata.setObjectName("adddata")
        adddata.resize(384, 488)
        self.label = QtWidgets.QLabel(adddata)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(adddata)
        self.line.setGeometry(QtCore.QRect(0, 40, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.addBn = QtWidgets.QPushButton(adddata)
        self.addBn.setGeometry(QtCore.QRect(290, 440, 80, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.addBn.setFont(font)
        self.addBn.setObjectName("addBn")
        self.addbackBn = QtWidgets.QPushButton(adddata)
        self.addbackBn.setGeometry(QtCore.QRect(190, 440, 80, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.addbackBn.setFont(font)
        self.addbackBn.setObjectName("addbackBn")
        self.layoutWidget = QtWidgets.QWidget(adddata)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 311, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.add_user = QtWidgets.QLineEdit(self.layoutWidget)
        self.add_user.setObjectName("add_user")
        self.gridLayout.addWidget(self.add_user, 2, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.add_address = QtWidgets.QLineEdit(self.layoutWidget)
        self.add_address.setObjectName("add_address")
        self.gridLayout.addWidget(self.add_address, 3, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 2)
        self.add_num = QtWidgets.QLineEdit(self.layoutWidget)
        self.add_num.setObjectName("add_num")
        self.gridLayout.addWidget(self.add_num, 0, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.add_title = QtWidgets.QLineEdit(self.layoutWidget)
        self.add_title.setObjectName("add_title")
        self.gridLayout.addWidget(self.add_title, 1, 2, 1, 2)
        self.add_time = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.add_time.setObjectName("add_time")
        self.gridLayout.addWidget(self.add_time, 4, 2, 1, 2)
        self.add_process = QtWidgets.QComboBox(self.layoutWidget)
        self.add_process.setObjectName("add_process")
        self.add_process.addItem("")
        self.add_process.addItem("")
        self.gridLayout.addWidget(self.add_process, 5, 2, 1, 2)
        self.add_operation = QtWidgets.QComboBox(self.layoutWidget)
        self.add_operation.setObjectName("add_operation")
        self.add_operation.addItem("")
        self.add_operation.addItem("")
        self.gridLayout.addWidget(self.add_operation, 6, 2, 1, 2)
        self.deleteBn = QtWidgets.QPushButton(adddata)
        self.deleteBn.setGeometry(QtCore.QRect(30, 440, 80, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.deleteBn.setFont(font)
        self.deleteBn.setObjectName("deleteBn")

        self.retranslateUi(adddata)
        self.deleteBn.clicked.connect(self.add_num.clear)
        self.deleteBn.clicked.connect(self.add_title.clear)
        self.deleteBn.clicked.connect(self.add_user.clear)
        self.deleteBn.clicked.connect(self.add_address.clear)
        QtCore.QMetaObject.connectSlotsByName(adddata)

    def retranslateUi(self, adddata):
        _translate = QtCore.QCoreApplication.translate
        adddata.setWindowTitle(_translate("adddata", "Form"))
        self.label.setText(_translate("adddata", "<html><head/><body><p><span style=\" font-size:16pt;\">添加数据</span></p></body></html>"))
        self.addBn.setText(_translate("adddata", "添加"))
        self.addbackBn.setText(_translate("adddata", "返回"))
        self.label_6.setText(_translate("adddata", "<html><head/><body><p align=\"center\">发布时间</p></body></html>"))
        self.label_4.setText(_translate("adddata", "<html><head/><body><p align=\"center\">用户</p></body></html>"))
        self.label_5.setText(_translate("adddata", "<html><head/><body><p align=\"center\">籍贯</p></body></html>"))
        self.label_7.setText(_translate("adddata", "<html><head/><body><p align=\"center\">是否审核</p></body></html>"))
        self.label_8.setText(_translate("adddata", "<html><head/><body><p align=\"center\">操作</p></body></html>"))
        self.label_2.setText(_translate("adddata", "<html><head/><body><p align=\"center\">编号</p></body></html>"))
        self.label_3.setText(_translate("adddata", "<html><head/><body><p align=\"center\">标题</p></body></html>"))
        self.add_process.setItemText(0, _translate("adddata", "已审核"))
        self.add_process.setItemText(1, _translate("adddata", "未审核"))
        self.add_operation.setItemText(0, _translate("adddata", "已审核"))
        self.add_operation.setItemText(1, _translate("adddata", "未审核"))
        self.deleteBn.setText(_translate("adddata", "清空"))

