# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showdata.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_showdata(object):
    def setupUi(self, showdata):
        showdata.setObjectName("showdata")
        showdata.resize(370, 502)
        self.showbackBn = QtWidgets.QPushButton(showdata)
        self.showbackBn.setGeometry(QtCore.QRect(240, 430, 80, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.showbackBn.setFont(font)
        self.showbackBn.setObjectName("showbackBn")
        self.layoutWidget = QtWidgets.QWidget(showdata)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 80, 281, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.show_num = QtWidgets.QLineEdit(self.layoutWidget)
        self.show_num.setObjectName("show_num")
        self.gridLayout.addWidget(self.show_num, 0, 2, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.show_title = QtWidgets.QLineEdit(self.layoutWidget)
        self.show_title.setObjectName("show_title")
        self.gridLayout.addWidget(self.show_title, 1, 2, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.show_user = QtWidgets.QLineEdit(self.layoutWidget)
        self.show_user.setObjectName("show_user")
        self.gridLayout.addWidget(self.show_user, 2, 2, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 2)
        self.show_address = QtWidgets.QLineEdit(self.layoutWidget)
        self.show_address.setObjectName("show_address")
        self.gridLayout.addWidget(self.show_address, 3, 2, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 2)
        self.show_time = QtWidgets.QLineEdit(self.layoutWidget)
        self.show_time.setObjectName("show_time")
        self.gridLayout.addWidget(self.show_time, 4, 2, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 2)
        self.show_process = QtWidgets.QLineEdit(self.layoutWidget)
        self.show_process.setObjectName("show_process")
        self.gridLayout.addWidget(self.show_process, 5, 2, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 2)
        self.show_operation = QtWidgets.QLineEdit(self.layoutWidget)
        self.show_operation.setObjectName("show_operation")
        self.gridLayout.addWidget(self.show_operation, 6, 2, 1, 3)
        self.line = QtWidgets.QFrame(showdata)
        self.line.setGeometry(QtCore.QRect(0, 40, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(showdata)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label.setObjectName("label")

        self.retranslateUi(showdata)
        QtCore.QMetaObject.connectSlotsByName(showdata)

    def retranslateUi(self, showdata):
        _translate = QtCore.QCoreApplication.translate
        showdata.setWindowTitle(_translate("showdata", "Form"))
        self.showbackBn.setText(_translate("showdata", "返回"))
        self.label_2.setText(_translate("showdata", "<html><head/><body><p align=\"center\">编号</p></body></html>"))
        self.label_3.setText(_translate("showdata", "<html><head/><body><p align=\"center\">标题</p></body></html>"))
        self.label_4.setText(_translate("showdata", "<html><head/><body><p align=\"center\">用户</p></body></html>"))
        self.label_5.setText(_translate("showdata", "<html><head/><body><p align=\"center\">籍贯</p></body></html>"))
        self.label_6.setText(_translate("showdata", "<html><head/><body><p align=\"center\">发布时间</p></body></html>"))
        self.label_7.setText(_translate("showdata", "<html><head/><body><p align=\"center\">是否审核</p></body></html>"))
        self.label_8.setText(_translate("showdata", "<html><head/><body><p align=\"center\">操作</p></body></html>"))
        self.label.setText(_translate("showdata", "<html><head/><body><p><span style=\" font-size:16pt;\">查看数据</span></p></body></html>"))

