# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sys.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Sys(object):
    def setupUi(self, Sys):
        Sys.setObjectName("Sys")
        Sys.resize(1204, 855)
        self.centralwidget = QtWidgets.QWidget(Sys)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 61))
        self.label.setObjectName("label")
        self.ExitBn = QtWidgets.QPushButton(self.centralwidget)
        self.ExitBn.setGeometry(QtCore.QRect(1040, 40, 80, 26))
        self.ExitBn.setObjectName("ExitBn")
        self.backBn = QtWidgets.QPushButton(self.centralwidget)
        self.backBn.setGeometry(QtCore.QRect(940, 40, 80, 26))
        self.backBn.setObjectName("backBn")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 1121, 731))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scoreBn = QtWidgets.QPushButton(self.frame)
        self.scoreBn.setGeometry(QtCore.QRect(0, 160, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scoreBn.setFont(font)
        self.scoreBn.setObjectName("scoreBn")
        self.InfBn = QtWidgets.QPushButton(self.frame)
        self.InfBn.setGeometry(QtCore.QRect(0, 80, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.InfBn.setFont(font)
        self.InfBn.setObjectName("InfBn")
        self.homeBn = QtWidgets.QPushButton(self.frame)
        self.homeBn.setGeometry(QtCore.QRect(0, 0, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.homeBn.setFont(font)
        self.homeBn.setObjectName("homeBn")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Pdata = QtWidgets.QStackedWidget(self.frame_2)
        self.Pdata.setGeometry(QtCore.QRect(-10, 0, 1001, 741))
        self.Pdata.setObjectName("Pdata")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 991, 721))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Statistical_data = QtWidgets.QTableWidget(self.layoutWidget1)
        self.Statistical_data.setObjectName("Statistical_data")
        self.Statistical_data.setColumnCount(0)
        self.Statistical_data.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.Statistical_data)
        self.Statistical_data_3 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.Statistical_data_3.setObjectName("Statistical_data_3")
        self.Statistical_data_3.setColumnCount(0)
        self.Statistical_data_3.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.Statistical_data_3)
        self.Statistical_data_2 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.Statistical_data_2.setObjectName("Statistical_data_2")
        self.Statistical_data_2.setColumnCount(0)
        self.Statistical_data_2.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.Statistical_data_2)
        self.Statistical_data_4 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.Statistical_data_4.setObjectName("Statistical_data_4")
        self.Statistical_data_4.setColumnCount(0)
        self.Statistical_data_4.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.Statistical_data_4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.Notice = QtWidgets.QListWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.Notice.sizePolicy().hasHeightForWidth())
        self.Notice.setSizePolicy(sizePolicy)
        self.Notice.setObjectName("Notice")
        self.gridLayout.addWidget(self.Notice, 2, 0, 1, 1)
        self.Tips = QtWidgets.QListWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.Tips.sizePolicy().hasHeightForWidth())
        self.Tips.setSizePolicy(sizePolicy)
        self.Tips.setObjectName("Tips")
        self.gridLayout.addWidget(self.Tips, 2, 1, 1, 1)
        self.Graph_data = QtWidgets.QTabWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.Graph_data.sizePolicy().hasHeightForWidth())
        self.Graph_data.setSizePolicy(sizePolicy)
        self.Graph_data.setObjectName("Graph_data")
        self.pie = QtWidgets.QWidget()
        self.pie.setObjectName("pie")
        self.pieplot = MatplotlibWidget(self.pie)
        self.pieplot.setGeometry(QtCore.QRect(0, 0, 441, 221))
        self.pieplot.setObjectName("pieplot")
        self.Graph_data.addTab(self.pie, "")
        self.graph = QtWidgets.QWidget()
        self.graph.setObjectName("graph")
        self.graphplot = QtWidgets.QWidget(self.graph)
        self.graphplot.setGeometry(QtCore.QRect(0, 0, 431, 221))
        self.graphplot.setObjectName("graphplot")
        self.Graph_data.addTab(self.graph, "")
        self.gridLayout.addWidget(self.Graph_data, 1, 1, 1, 1)
        self.map = QtWidgets.QTextEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map.sizePolicy().hasHeightForWidth())
        self.map.setSizePolicy(sizePolicy)
        self.map.setObjectName("map")
        self.gridLayout.addWidget(self.map, 1, 0, 1, 1)
        self.Pdata.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.data = QtWidgets.QTableWidget(self.page_4)
        self.data.setGeometry(QtCore.QRect(10, 110, 991, 591))
        self.data.setObjectName("data")
        self.data.setColumnCount(0)
        self.data.setRowCount(0)
        self.layoutWidget2 = QtWidgets.QWidget(self.page_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 681, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.search_num = QtWidgets.QLineEdit(self.layoutWidget2)
        self.search_num.setObjectName("search_num")
        self.gridLayout_2.addWidget(self.search_num, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.search_user = QtWidgets.QLineEdit(self.layoutWidget2)
        self.search_user.setObjectName("search_user")
        self.gridLayout_2.addWidget(self.search_user, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 4, 1, 1)
        self.search_adress = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_adress.sizePolicy().hasHeightForWidth())
        self.search_adress.setSizePolicy(sizePolicy)
        self.search_adress.setObjectName("search_adress")
        self.gridLayout_2.addWidget(self.search_adress, 0, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.search_title = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_title.sizePolicy().hasHeightForWidth())
        self.search_title.setSizePolicy(sizePolicy)
        self.search_title.setObjectName("search_title")
        self.gridLayout_2.addWidget(self.search_title, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.search_time = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_time.sizePolicy().hasHeightForWidth())
        self.search_time.setSizePolicy(sizePolicy)
        self.search_time.setObjectName("search_time")
        self.gridLayout_2.addWidget(self.search_time, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 4, 1, 1)
        self.search_keyword = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_keyword.sizePolicy().hasHeightForWidth())
        self.search_keyword.setSizePolicy(sizePolicy)
        self.search_keyword.setObjectName("search_keyword")
        self.gridLayout_2.addWidget(self.search_keyword, 1, 5, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.page_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(710, 20, 291, 81))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.showBn = QtWidgets.QPushButton(self.layoutWidget3)
        self.showBn.setObjectName("showBn")
        self.gridLayout_3.addWidget(self.showBn, 0, 0, 1, 1)
        self.addBn = QtWidgets.QPushButton(self.layoutWidget3)
        self.addBn.setObjectName("addBn")
        self.gridLayout_3.addWidget(self.addBn, 0, 1, 1, 1)
        self.delBn = QtWidgets.QPushButton(self.layoutWidget3)
        self.delBn.setObjectName("delBn")
        self.gridLayout_3.addWidget(self.delBn, 0, 2, 1, 1)
        self.searchBn = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBn.sizePolicy().hasHeightForWidth())
        self.searchBn.setSizePolicy(sizePolicy)
        self.searchBn.setObjectName("searchBn")
        self.gridLayout_3.addWidget(self.searchBn, 1, 0, 1, 1)
        self.clearBn = QtWidgets.QPushButton(self.layoutWidget3)
        self.clearBn.setObjectName("clearBn")
        self.gridLayout_3.addWidget(self.clearBn, 1, 1, 1, 1)
        self.corBn = QtWidgets.QPushButton(self.layoutWidget3)
        self.corBn.setObjectName("corBn")
        self.gridLayout_3.addWidget(self.corBn, 1, 2, 1, 1)
        self.layoutWidget.raise_()
        self.data.raise_()
        self.layoutWidget.raise_()
        self.Pdata.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.EvaBn = QtWidgets.QPushButton(self.page_5)
        self.EvaBn.setGeometry(QtCore.QRect(760, 100, 80, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EvaBn.setFont(font)
        self.EvaBn.setObjectName("EvaBn")
        self.widget_3 = QtWidgets.QWidget(self.page_5)
        self.widget_3.setGeometry(QtCore.QRect(40, 220, 861, 501))
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget4 = QtWidgets.QWidget(self.page_5)
        self.layoutWidget4.setGeometry(QtCore.QRect(40, 10, 701, 201))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.number = QtWidgets.QLabel(self.layoutWidget4)
        self.number.setObjectName("number")
        self.gridLayout_4.addWidget(self.number, 0, 0, 1, 1)
        self.Pnumber = QtWidgets.QComboBox(self.layoutWidget4)
        self.Pnumber.setObjectName("Pnumber")
        self.gridLayout_4.addWidget(self.Pnumber, 0, 1, 1, 1)
        self.Pname = QtWidgets.QLineEdit(self.layoutWidget4)
        self.Pname.setObjectName("Pname")
        self.gridLayout_4.addWidget(self.Pname, 0, 3, 1, 1)
        self.Pkeyword = QtWidgets.QLabel(self.layoutWidget4)
        self.Pkeyword.setObjectName("Pkeyword")
        self.gridLayout_4.addWidget(self.Pkeyword, 0, 4, 1, 1)
        self.Pkeywords = QtWidgets.QLineEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pkeywords.sizePolicy().hasHeightForWidth())
        self.Pkeywords.setSizePolicy(sizePolicy)
        self.Pkeywords.setObjectName("Pkeywords")
        self.gridLayout_4.addWidget(self.Pkeywords, 0, 5, 1, 1)
        self.address = QtWidgets.QLabel(self.layoutWidget4)
        self.address.setObjectName("address")
        self.gridLayout_4.addWidget(self.address, 1, 0, 1, 1)
        self.Paddress1 = QtWidgets.QComboBox(self.layoutWidget4)
        self.Paddress1.setObjectName("Paddress1")
        self.gridLayout_4.addWidget(self.Paddress1, 1, 1, 1, 1)
        self.Paddress2 = QtWidgets.QComboBox(self.layoutWidget4)
        self.Paddress2.setObjectName("Paddress2")
        self.gridLayout_4.addWidget(self.Paddress2, 1, 2, 1, 1)
        self.Paddress3 = QtWidgets.QComboBox(self.layoutWidget4)
        self.Paddress3.setObjectName("Paddress3")
        self.gridLayout_4.addWidget(self.Paddress3, 1, 3, 1, 1)
        self.namedata = QtWidgets.QLabel(self.layoutWidget4)
        self.namedata.setObjectName("namedata")
        self.gridLayout_4.addWidget(self.namedata, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.Pdata.addWidget(self.page_5)
        self.horizontalLayout.addWidget(self.frame_2)
        self.layoutWidget.raise_()
        self.label.raise_()
        self.ExitBn.raise_()
        self.backBn.raise_()
        Sys.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Sys)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1204, 23))
        self.menubar.setObjectName("menubar")
        Sys.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Sys)
        self.statusbar.setObjectName("statusbar")
        Sys.setStatusBar(self.statusbar)

        self.retranslateUi(Sys)
        self.Pdata.setCurrentIndex(0)
        self.Graph_data.setCurrentIndex(0)
        self.clearBn.clicked.connect(self.data.clearContents)
        QtCore.QMetaObject.connectSlotsByName(Sys)

    def retranslateUi(self, Sys):
        _translate = QtCore.QCoreApplication.translate
        Sys.setWindowTitle(_translate("Sys", "MainWindow"))
        self.label.setText(_translate("Sys", "<html><head/><body><p><span style=\" font-size:24pt;\">信息管理系统</span></p></body></html>"))
        self.ExitBn.setText(_translate("Sys", "退出"))
        self.backBn.setText(_translate("Sys", "返回"))
        self.scoreBn.setText(_translate("Sys", "信息评价"))
        self.InfBn.setText(_translate("Sys", "信息管理"))
        self.homeBn.setText(_translate("Sys", "主页"))
        self.Graph_data.setTabText(self.Graph_data.indexOf(self.pie), _translate("Sys", "Tab 1"))
        self.Graph_data.setTabText(self.Graph_data.indexOf(self.graph), _translate("Sys", "Tab 2"))
        self.label_4.setText(_translate("Sys", "<html><head/><body><p><span style=\" font-size:12pt;\">编号</span></p></body></html>"))
        self.label_2.setText(_translate("Sys", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">用户</span></p></body></html>"))
        self.label_3.setText(_translate("Sys", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">籍贯</span></p></body></html>"))
        self.label_5.setText(_translate("Sys", "<html><head/><body><p><span style=\" font-size:12pt;\">标题</span></p></body></html>"))
        self.label_12.setText(_translate("Sys", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">发布时间</span></p></body></html>"))
        self.label_13.setText(_translate("Sys", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">关键字</span></p></body></html>"))
        self.showBn.setText(_translate("Sys", "查看"))
        self.addBn.setText(_translate("Sys", "添加"))
        self.delBn.setText(_translate("Sys", "删除"))
        self.searchBn.setText(_translate("Sys", "查询"))
        self.clearBn.setText(_translate("Sys", "清空"))
        self.corBn.setText(_translate("Sys", "修改"))
        self.EvaBn.setText(_translate("Sys", "评估"))
        self.label_6.setText(_translate("Sys", "<html><head/><body><p><span style=\" font-size:18pt;\">评估</span></p></body></html>"))
        self.number.setText(_translate("Sys", "<html><head/><body><p><span style=\" font-size:12pt;\">编号</span></p></body></html>"))
        self.Pkeyword.setText(_translate("Sys", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">关键字</span></p></body></html>"))
        self.address.setText(_translate("Sys", "<html><head/><body><p><span style=\" font-size:12pt;\">地址</span></p></body></html>"))
        self.namedata.setText(_translate("Sys", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">名称</span></p></body></html>"))
        self.label_11.setText(_translate("Sys", "<html><head/><body><p><span style=\" font-size:14pt;\">评估结果</span></p></body></html>"))

from MatplotlibWidget import MatplotlibWidget
